feat: Initiated benchmark workflow
casbin/casbin-cpp pull request #114
Opened 2021-06-28 23:37 UTC by EmperorYP7

### Fixes #42

Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

---

### Description

This code will find [google/benchmark v1.5.5](https://github.com/google/benchmark) within the system. If not found, it will fetch it from GitHub and store it in `build/_deps` directory. Here's the workflow to get it running:

1. Checkout to `EmperorYP7/casbin-cpp:benchmark`.
2. Build the project using the commands stated in docs to be added in #113.
3. Go to `/build/tests/benchmarks` and run the executable named `casbin_benchmark`

2021-06-29 12:57 UTC, EmperorYP7 commented
@hsluoyz Should I add a CI workflow for showing benchmarks?

2021-06-29 14:26 UTC, hsluoyz commented
@EmperorYP7 yes, of course!

2021-06-29 17:38 UTC, EmperorYP7 commented
@hsluoyz Benchmark results can be viewed here https://github.com/casbin/casbin-cpp/pull/114/checks?check_run_id=2944894498

2021-06-30 10:49 UTC, hsluoyz requested changes

2021-06-30 10:49 UTC, hsluoyz commented on .github/workflows/benchmark.yml
> +#  Copyright 2020 The casbin Authors. All Rights Reserved.
Plz use `2021` for newly added source code file.

2021-06-30 10:57 UTC, hsluoyz approved these changes

2021-06-30 10:59 UTC, hsluoyz requested changes

2021-06-30 10:59 UTC, hsluoyz commented on CMakeLists.txt
> +#  Copyright 2021 The casbin Authors. All Rights Reserved.
Don't update year for old files.

2021-06-30 10:59 UTC, hsluoyz commented on tests/benchmarks/main.cpp
> +* Copyright 2020 The casbin Authors. All Rights Reserved.
Use now year for new files.

2021-06-30 10:59 UTC, hsluoyz commented on tests/benchmarks/enforcer_cached_b.cpp
> +* Copyright 2020 The casbin Authors. All Rights Reserved.
Use now year for new files.

2021-06-30 11:20 UTC, EmperorYP7 commented on CMakeLists.txt
> +#  Copyright 2021 The casbin Authors. All Rights Reserved.
Fixed

2021-06-30 11:21 UTC, EmperorYP7 commented on tests/benchmarks/main.cpp
> +* Copyright 2020 The casbin Authors. All Rights Reserved.
Fixed

2021-06-30 11:24 UTC, merged