feat: add eval regex and test
casbin/casbin-cpp pull request #167
Opened 2021-11-17 03:51 UTC by sheny1xuan

Signed-off-by: stonex <1479765922@qq.com>

### Description
+ In adac model, we need test `eavl()` whether in the model matcher expression. Add a regex to test whether has `eval`.
+ `ReplaceEvalWithMap` replace the `eval(tokens)` by tokens value.
+ Add an unit test for `eval()`.

2021-11-17 05:19 UTC, hsluoyz commented
@EmperorYP7 plz review

2021-11-18 17:14 UTC, EmperorYP7 requested changes
Saving a few constructor calls might help in case expression is evaluated over a million times.

2021-11-18 17:14 UTC, EmperorYP7 commented on casbin/util/eval.cpp
> +bool HasEval(std::string s) {
```suggestion
bool HasEval(const std::string& s) {
```

2021-11-18 17:14 UTC, EmperorYP7 commented on casbin/util/util.h
> +bool HasEval(std::string s);
```suggestion
bool HasEval(const std::string& s);
```

2021-11-18 17:14 UTC, EmperorYP7 commented on include/casbin/casbin_helpers.h
> +    bool HasEval(std::string s);
```suggestion
    bool HasEval(const std::string& s);
```

2021-11-19 03:06 UTC, sheny1xuan commented on casbin/util/eval.cpp
> +bool HasEval(std::string s) {
Have fixed it.

2021-11-19 03:30 UTC, sheny1xuan commented
I think this pr can be merged now, and I will make a new pr base this. @hsluoyz

2021-11-19 08:31 UTC, merged