perf: Remove shared_ptr in defaultRoleManager
casbin/casbin-cpp pull request #206
Opened 2022-07-10 06:31 UTC by sheny1xuan

* Share_ptr will cause performance loss.
	* Share_ptr may cause circular reference of Roles, which will cause memeory leak.
	* RoleManager take ownership of the resource, responsible for the application and release of Role*, Role only use this pointer.

Signed-off-by: Stonexx <1479765922@qq.com>

## Fixes # <Enter the issue number>

### Description

### Screenshots/Testimonials

2022-07-10 07:35 UTC, hsluoyz commented
@EmperorYP7

2022-07-10 16:48 UTC, EmperorYP7 requested changes

2022-07-10 16:48 UTC, EmperorYP7 commented on casbin/rbac/default_role_manager.cpp
> +std::unique_ptr<Role> Role :: NewRole(std::string name) {
```suggestion
std::unique_ptr<Role> Role :: NewRole(const std::string& name) {
```

2022-07-10 16:48 UTC, EmperorYP7 commented on casbin/rbac/default_role_manager.cpp
> +                Role* role1;
```suggestion
                Role* role1 = nullptr;
```

2022-07-10 16:48 UTC, EmperorYP7 commented on include/casbin/rbac/default_role_manager.h
> +    Role* CreateRole(std::string name);
```suggestion
    Role* CreateRole(const std::string& name);
```

2022-07-20 16:58 UTC, EmperorYP7 approved these changes
LGTM

2022-07-20 16:58 UTC, merged