Add synced enforcer and util for it.
casbin/casbin-cpp pull request #67
Opened 2020-09-30 06:32 UTC by ZipoChan

Add go-style channel.
Add synced enforcer.

2020-09-30 11:53 UTC, hsluoyz commented
@ZipoChan please fix:

![image](https://user-images.githubusercontent.com/3787410/94681784-92ce5a80-0356-11eb-9d2f-69ab70a63fc5.png)

2020-10-01 02:01 UTC, hsluoyz commented
@xcaptain @divy9881 please review.

2020-10-27 04:05 UTC, divy9881 requested changes

2020-10-27 04:05 UTC, divy9881 commented on casbin/enforcer_synced.h
> +    Channel<int> stopAutoLoad;
The stopAutoLoad is never being used anywhere as a channel.

2020-10-27 04:05 UTC, divy9881 commented on casbin/enforcer_synced.cpp
> +void SyncedEnforcer::StartAutoLoadPolicy(chrono::duration<int, milli> duration) {
You need to fix this function, it seems that it's not functional.

2021-01-07 12:30 UTC, divy9881 commented
@ZipoChan, please fix the compile-time errors and changes requested.

2021-02-13 03:19 UTC, hsluoyz commented
Closed as stale.

2021-02-13 03:19 UTC, closed without merging